version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/static_root
      - media_volume:/app/media
    environment:
      - DEBUG=True
      - NOVA_POSHTA_API_KEY=${NOVA_POSHTA_API_KEY}
      - DB_ENGINE=django.db.backends.sqlite3
      - DB_NAME=/app/db.sqlite3
    command: sh -c "python manage.py migrate && python manage.py collectstatic --noinput && python manage.py runserver 0.0.0.0:8000"

volumes:
  static_volume:
  media_volume: 